// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

module.exports = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+common:(.+)$': './packages/common/src/$1',
    '^multiverse\\+next\\x2dadhesive:(.+)$': './packages/next-adhesive/src/$1',
    '^multiverse\\+next\\x2dapi\\x2dglue:(.+)$': './packages/next-api-glue/src/$1',
    '^multiverse\\+next\\x2dapi\\x2drespond:(.+)$': './packages/next-api-respond/src/$1',
    '^multiverse\\+next\\x2dauth:(.+)$': './packages/next-auth/src/$1',
    '^multiverse\\+next\\x2dcontrived:(.+)$': './packages/next-contrived/src/$1',
    '^multiverse\\+next\\x2denv:(.+)$': './packages/next-env/src/$1',
    '^multiverse\\+next\\x2dlimit:(.+)$': './packages/next-limit/src/$1',
    '^multiverse\\+next\\x2dlog:(.+)$': './packages/next-log/src/$1',
    '^multiverse\\+common$': './packages/common/src/index.js',
    '^multiverse\\+next\\x2dadhesive$': './packages/next-adhesive/src/index.js',
    '^multiverse\\+next\\x2dapi\\x2dglue$': './packages/next-api-glue/src/index.js',
    '^multiverse\\+next\\x2dapi\\x2drespond$': './packages/next-api-respond/src/index.js',
    '^multiverse\\+next\\x2dauth$': './packages/next-auth/src/index.js',
    '^multiverse\\+next\\x2dcontrived$': './packages/next-contrived/src/index.js',
    '^multiverse\\+next\\x2denv$': './packages/next-env/src/index.js',
    '^multiverse\\+next\\x2dlimit$': './packages/next-limit/src/index.js',
    '^multiverse\\+next\\x2dlog$': './packages/next-log/src/index.js',
    '^universe\\+common:(.+)$': './packages/common/src/$1',
    '^universe\\+next\\x2dadhesive:(.+)$': './packages/next-adhesive/src/$1',
    '^universe\\+next\\x2dapi\\x2dglue:(.+)$': './packages/next-api-glue/src/$1',
    '^universe\\+next\\x2dapi\\x2drespond:(.+)$': './packages/next-api-respond/src/$1',
    '^universe\\+next\\x2dauth:(.+)$': './packages/next-auth/src/$1',
    '^universe\\+next\\x2dcontrived:(.+)$': './packages/next-contrived/src/$1',
    '^universe\\+next\\x2denv:(.+)$': './packages/next-env/src/$1',
    '^universe\\+next\\x2dlimit:(.+)$': './packages/next-limit/src/$1',
    '^universe\\+next\\x2dlog:(.+)$': './packages/next-log/src/$1',
    '^universe\\+common$': './packages/common/src/index.js',
    '^universe\\+next\\x2dadhesive$': './packages/next-adhesive/src/index.js',
    '^universe\\+next\\x2dapi\\x2dglue$': './packages/next-api-glue/src/index.js',
    '^universe\\+next\\x2dapi\\x2drespond$': './packages/next-api-respond/src/index.js',
    '^universe\\+next\\x2dauth$': './packages/next-auth/src/index.js',
    '^universe\\+next\\x2dcontrived$': './packages/next-contrived/src/index.js',
    '^universe\\+next\\x2denv$': './packages/next-env/src/index.js',
    '^universe\\+next\\x2dlimit$': './packages/next-limit/src/index.js',
    '^universe\\+next\\x2dlog$': './packages/next-log/src/index.js',
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse\\+common:(.+)$': './packages/common/test/$1',
    '^testverse\\+next\\x2dadhesive:(.+)$': './packages/next-adhesive/test/$1',
    '^testverse\\+next\\x2dapi\\x2dglue:(.+)$': './packages/next-api-glue/test/$1',
    '^testverse\\+next\\x2dapi\\x2drespond:(.+)$': './packages/next-api-respond/test/$1',
    '^testverse\\+next\\x2dauth:(.+)$': './packages/next-auth/test/$1',
    '^testverse\\+next\\x2dcontrived:(.+)$': './packages/next-contrived/test/$1',
    '^testverse\\+next\\x2denv:(.+)$': './packages/next-env/test/$1',
    '^testverse\\+next\\x2dlimit:(.+)$': './packages/next-limit/test/$1',
    '^testverse\\+next\\x2dlog:(.+)$': './packages/next-log/test/$1',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1',
    '^rootverse\\+common:(.+)$': './packages/common/$1',
    '^rootverse\\+next\\x2dadhesive:(.+)$': './packages/next-adhesive/$1',
    '^rootverse\\+next\\x2dapi\\x2dglue:(.+)$': './packages/next-api-glue/$1',
    '^rootverse\\+next\\x2dapi\\x2drespond:(.+)$': './packages/next-api-respond/$1',
    '^rootverse\\+next\\x2dauth:(.+)$': './packages/next-auth/$1',
    '^rootverse\\+next\\x2dcontrived:(.+)$': './packages/next-contrived/$1',
    '^rootverse\\+next\\x2denv:(.+)$': './packages/next-env/$1',
    '^rootverse\\+next\\x2dlimit:(.+)$': './packages/next-limit/$1',
    '^rootverse\\+next\\x2dlog:(.+)$': './packages/next-log/$1',
    '^rootverse:(.+)$': './$1'
  };
}
