// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

module.exports = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
    // You may wish to enable explicit exports references for improved testing
    // DX, but be aware that it is currently a wee buggy as of 5/2025 (fix it!)
    //
    // env: {
    //   test: {
    //     plugins: ['babel-plugin-explicit-exports-references']
    //   }
    // }
  }
);

debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+next\\x2dapi:(.+)$': './packages/next-api/src/$1',
    '^multiverse\\+next\\x2dapi\\x2dcommon:(.+)$': './packages/next-api-common/src/$1',
    '^multiverse\\+next\\x2denv:(.+)$': './packages/next-env/src/$1',
    '^multiverse\\+shared:(.+)$': './packages/shared/src/$1',
    '^multiverse\\+next\\x2dapi$': './packages/next-api/src/index.js',
    '^multiverse\\+next\\x2dapi\\x2dcommon$': './packages/next-api-common/src/index.js',
    '^multiverse\\+next\\x2denv$': './packages/next-env/src/index.js',
    '^multiverse\\+shared$': './packages/shared/src/index.js',
    '^universe\\+next\\x2dapi:(.+)$': './packages/next-api/src/$1',
    '^universe\\+next\\x2dapi\\x2dcommon:(.+)$': './packages/next-api-common/src/$1',
    '^universe\\+next\\x2denv:(.+)$': './packages/next-env/src/$1',
    '^universe\\+shared:(.+)$': './packages/shared/src/$1',
    '^universe\\+next\\x2dapi$': './packages/next-api/src/index.js',
    '^universe\\+next\\x2dapi\\x2dcommon$': './packages/next-api-common/src/index.js',
    '^universe\\+next\\x2denv$': './packages/next-env/src/index.js',
    '^universe\\+shared$': './packages/shared/src/index.js',
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse\\+next\\x2dapi:(.+)$': './packages/next-api/test/$1',
    '^testverse\\+next\\x2dapi\\x2dcommon:(.+)$': './packages/next-api-common/test/$1',
    '^testverse\\+next\\x2denv:(.+)$': './packages/next-env/test/$1',
    '^testverse\\+shared:(.+)$': './packages/shared/test/$1',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1',
    '^rootverse\\+next\\x2dapi:(.+)$': './packages/next-api/$1',
    '^rootverse\\+next\\x2dapi\\x2dcommon:(.+)$': './packages/next-api-common/$1',
    '^rootverse\\+next\\x2denv:(.+)$': './packages/next-env/$1',
    '^rootverse\\+shared:(.+)$': './packages/shared/$1',
    '^rootverse:(.+)$': './$1'
  };
}
