// @ts-check

import { assertEnvironment, moduleExport } from '@-xun/symbiote/assets/eslint.config.mjs';

import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:eslint' });

const config = await moduleExport({
  derivedAliases: getEslintAliases(),
  ...(await assertEnvironment())
});

config.push({
  /* Add custom config here, such as disabling certain rules */
});

export default config;

debug('exported config: %O', config);

function getEslintAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return [
    ['multiverse+common:*', './packages/common/src/*'],
    ['multiverse+next-adhesive:*', './packages/next-adhesive/src/*'],
    ['multiverse+next-api-glue:*', './packages/next-api-glue/src/*'],
    ['multiverse+next-api-respond:*', './packages/next-api-respond/src/*'],
    ['multiverse+next-auth:*', './packages/next-auth/src/*'],
    ['multiverse+next-contrived:*', './packages/next-contrived/src/*'],
    ['multiverse+next-env:*', './packages/next-env/src/*'],
    ['multiverse+next-limit:*', './packages/next-limit/src/*'],
    ['multiverse+next-log:*', './packages/next-log/src/*'],
    ['multiverse+common', './packages/common/src/index.ts'],
    ['multiverse+next-adhesive', './packages/next-adhesive/src/index.ts'],
    ['multiverse+next-api-glue', './packages/next-api-glue/src/index.ts'],
    ['multiverse+next-api-respond', './packages/next-api-respond/src/index.ts'],
    ['multiverse+next-auth', './packages/next-auth/src/index.ts'],
    ['multiverse+next-contrived', './packages/next-contrived/src/index.ts'],
    ['multiverse+next-env', './packages/next-env/src/index.ts'],
    ['multiverse+next-limit', './packages/next-limit/src/index.ts'],
    ['multiverse+next-log', './packages/next-log/src/index.ts'],
    ['rootverse+common:*', './packages/common/*'],
    ['rootverse+next-adhesive:*', './packages/next-adhesive/*'],
    ['rootverse+next-api-glue:*', './packages/next-api-glue/*'],
    ['rootverse+next-api-respond:*', './packages/next-api-respond/*'],
    ['rootverse+next-auth:*', './packages/next-auth/*'],
    ['rootverse+next-contrived:*', './packages/next-contrived/*'],
    ['rootverse+next-env:*', './packages/next-env/*'],
    ['rootverse+next-limit:*', './packages/next-limit/*'],
    ['rootverse+next-log:*', './packages/next-log/*'],
    ['rootverse:*', './*'],
    ['universe+common:*', './packages/common/src/*'],
    ['universe+next-adhesive:*', './packages/next-adhesive/src/*'],
    ['universe+next-api-glue:*', './packages/next-api-glue/src/*'],
    ['universe+next-api-respond:*', './packages/next-api-respond/src/*'],
    ['universe+next-auth:*', './packages/next-auth/src/*'],
    ['universe+next-contrived:*', './packages/next-contrived/src/*'],
    ['universe+next-env:*', './packages/next-env/src/*'],
    ['universe+next-limit:*', './packages/next-limit/src/*'],
    ['universe+next-log:*', './packages/next-log/src/*'],
    ['universe+common', './packages/common/src/index.ts'],
    ['universe+next-adhesive', './packages/next-adhesive/src/index.ts'],
    ['universe+next-api-glue', './packages/next-api-glue/src/index.ts'],
    ['universe+next-api-respond', './packages/next-api-respond/src/index.ts'],
    ['universe+next-auth', './packages/next-auth/src/index.ts'],
    ['universe+next-contrived', './packages/next-contrived/src/index.ts'],
    ['universe+next-env', './packages/next-env/src/index.ts'],
    ['universe+next-limit', './packages/next-limit/src/index.ts'],
    ['universe+next-log', './packages/next-log/src/index.ts'],
    ['universe:*', './src/*'],
    ['universe', './src/index.ts'],
    ['testverse+common:*', './packages/common/test/*'],
    ['testverse+next-adhesive:*', './packages/next-adhesive/test/*'],
    ['testverse+next-api-glue:*', './packages/next-api-glue/test/*'],
    ['testverse+next-api-respond:*', './packages/next-api-respond/test/*'],
    ['testverse+next-auth:*', './packages/next-auth/test/*'],
    ['testverse+next-contrived:*', './packages/next-contrived/test/*'],
    ['testverse+next-env:*', './packages/next-env/test/*'],
    ['testverse+next-limit:*', './packages/next-limit/test/*'],
    ['testverse+next-log:*', './packages/next-log/test/*'],
    ['testverse:*', './test/*'],
    ['typeverse:*', './types/*']
  ];
}
