// @ts-check
'use strict';

import { deepMergeConfig } from '@-xun/symbiote/assets';
import { assertEnvironment, moduleExport } from '@-xun/symbiote/assets/jest.config.mjs';
import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:jest' });

const config = deepMergeConfig(
  moduleExport({ derivedAliases: getJestAliases(), ...assertEnvironment() }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

export default config;

debug('exported config: %O', config);

function getJestAliases() {
  const extension = process.env.SYMBIOTE_TEST_JEST_TRANSPILED ? 'js' : 'ts';

  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+common:(.+)$': '<rootDir>/packages/common/src/$1',
    '^multiverse\\+next\\x2dadhesive:(.+)$': '<rootDir>/packages/next-adhesive/src/$1',
    '^multiverse\\+next\\x2dapi\\x2dglue:(.+)$':
      '<rootDir>/packages/next-api-glue/src/$1',
    '^multiverse\\+next\\x2dapi\\x2drespond:(.+)$':
      '<rootDir>/packages/next-api-respond/src/$1',
    '^multiverse\\+next\\x2dauth:(.+)$': '<rootDir>/packages/next-auth/src/$1',
    '^multiverse\\+next\\x2dcontrived:(.+)$': '<rootDir>/packages/next-contrived/src/$1',
    '^multiverse\\+next\\x2denv:(.+)$': '<rootDir>/packages/next-env/src/$1',
    '^multiverse\\+next\\x2dlimit:(.+)$': '<rootDir>/packages/next-limit/src/$1',
    '^multiverse\\+next\\x2dlog:(.+)$': '<rootDir>/packages/next-log/src/$1',
    '^multiverse\\+common$': `<rootDir>/packages/common/src/index.${extension}`,
    '^multiverse\\+next\\x2dadhesive$': `<rootDir>/packages/next-adhesive/src/index.${extension}`,
    '^multiverse\\+next\\x2dapi\\x2dglue$': `<rootDir>/packages/next-api-glue/src/index.${extension}`,
    '^multiverse\\+next\\x2dapi\\x2drespond$': `<rootDir>/packages/next-api-respond/src/index.${extension}`,
    '^multiverse\\+next\\x2dauth$': `<rootDir>/packages/next-auth/src/index.${extension}`,
    '^multiverse\\+next\\x2dcontrived$': `<rootDir>/packages/next-contrived/src/index.${extension}`,
    '^multiverse\\+next\\x2denv$': `<rootDir>/packages/next-env/src/index.${extension}`,
    '^multiverse\\+next\\x2dlimit$': `<rootDir>/packages/next-limit/src/index.${extension}`,
    '^multiverse\\+next\\x2dlog$': `<rootDir>/packages/next-log/src/index.${extension}`,
    '^universe\\+common:(.+)$': '<rootDir>/packages/common/src/$1',
    '^universe\\+next\\x2dadhesive:(.+)$': '<rootDir>/packages/next-adhesive/src/$1',
    '^universe\\+next\\x2dapi\\x2dglue:(.+)$': '<rootDir>/packages/next-api-glue/src/$1',
    '^universe\\+next\\x2dapi\\x2drespond:(.+)$':
      '<rootDir>/packages/next-api-respond/src/$1',
    '^universe\\+next\\x2dauth:(.+)$': '<rootDir>/packages/next-auth/src/$1',
    '^universe\\+next\\x2dcontrived:(.+)$': '<rootDir>/packages/next-contrived/src/$1',
    '^universe\\+next\\x2denv:(.+)$': '<rootDir>/packages/next-env/src/$1',
    '^universe\\+next\\x2dlimit:(.+)$': '<rootDir>/packages/next-limit/src/$1',
    '^universe\\+next\\x2dlog:(.+)$': '<rootDir>/packages/next-log/src/$1',
    '^universe\\+common$': `<rootDir>/packages/common/src/index.${extension}`,
    '^universe\\+next\\x2dadhesive$': `<rootDir>/packages/next-adhesive/src/index.${extension}`,
    '^universe\\+next\\x2dapi\\x2dglue$': `<rootDir>/packages/next-api-glue/src/index.${extension}`,
    '^universe\\+next\\x2dapi\\x2drespond$': `<rootDir>/packages/next-api-respond/src/index.${extension}`,
    '^universe\\+next\\x2dauth$': `<rootDir>/packages/next-auth/src/index.${extension}`,
    '^universe\\+next\\x2dcontrived$': `<rootDir>/packages/next-contrived/src/index.${extension}`,
    '^universe\\+next\\x2denv$': `<rootDir>/packages/next-env/src/index.${extension}`,
    '^universe\\+next\\x2dlimit$': `<rootDir>/packages/next-limit/src/index.${extension}`,
    '^universe\\+next\\x2dlog$': `<rootDir>/packages/next-log/src/index.${extension}`,
    '^universe:(.+)$': '<rootDir>/src/$1',
    '^universe$': `<rootDir>/src/index.${extension}`,
    '^testverse\\+common:(.+)$': '<rootDir>/packages/common/test/$1',
    '^testverse\\+next\\x2dadhesive:(.+)$': '<rootDir>/packages/next-adhesive/test/$1',
    '^testverse\\+next\\x2dapi\\x2dglue:(.+)$':
      '<rootDir>/packages/next-api-glue/test/$1',
    '^testverse\\+next\\x2dapi\\x2drespond:(.+)$':
      '<rootDir>/packages/next-api-respond/test/$1',
    '^testverse\\+next\\x2dauth:(.+)$': '<rootDir>/packages/next-auth/test/$1',
    '^testverse\\+next\\x2dcontrived:(.+)$': '<rootDir>/packages/next-contrived/test/$1',
    '^testverse\\+next\\x2denv:(.+)$': '<rootDir>/packages/next-env/test/$1',
    '^testverse\\+next\\x2dlimit:(.+)$': '<rootDir>/packages/next-limit/test/$1',
    '^testverse\\+next\\x2dlog:(.+)$': '<rootDir>/packages/next-log/test/$1',
    '^testverse:(.+)$': '<rootDir>/test/$1',
    '^typeverse:(.+)$': '<rootDir>/types/$1',
    '^rootverse\\+common:(.+)$': '<rootDir>/packages/common/$1',
    '^rootverse\\+next\\x2dadhesive:(.+)$': '<rootDir>/packages/next-adhesive/$1',
    '^rootverse\\+next\\x2dapi\\x2dglue:(.+)$': '<rootDir>/packages/next-api-glue/$1',
    '^rootverse\\+next\\x2dapi\\x2drespond:(.+)$':
      '<rootDir>/packages/next-api-respond/$1',
    '^rootverse\\+next\\x2dauth:(.+)$': '<rootDir>/packages/next-auth/$1',
    '^rootverse\\+next\\x2dcontrived:(.+)$': '<rootDir>/packages/next-contrived/$1',
    '^rootverse\\+next\\x2denv:(.+)$': '<rootDir>/packages/next-env/$1',
    '^rootverse\\+next\\x2dlimit:(.+)$': '<rootDir>/packages/next-limit/$1',
    '^rootverse\\+next\\x2dlog:(.+)$': '<rootDir>/packages/next-log/$1',
    '^rootverse:(.+)$': '<rootDir>/$1'
  };
}
